site_name: OYMotion
site_author: He Bin
copyright: CopyrightÂ© 2021 OYMotion Technologies,Inc.All rights reserved. 
theme:
  name: material
  palette:
    primary: 'orange'
    accent: 'deep orange'
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/favicon.ico'

nav:
  - Home: index.md
  - Products:
    - gForce200: ./gForce200/gForce200UserGuide.md
    - gForcePro/gForcePro+: ./gForcePro/gForcePro.md
    - gForceJoint: ./gForceJoint/gForceJoint.md

  - SDK:
      - SDK List: ./gForceSDK/SDKList.md
      - SDK Manual: ./gForceSDK/gForceSDK.md

  - APPs: 
      - OTrain: ./APPs/OTrain.md
      - gForceApp for gForce100/gForcePro: ./APPs/gForceAppLegacy.md
      - gForceApp for gForce200/gForcePro+: ./APPs/gForceApp.md
      - oym8CHWave: ./APPs/oym8CHWave.md
